matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1.201
      before_script:
        - cd server
      script:
        - dotnet test --verbosity n

    - language: node.js
      node_js: "12.0"
      before_script:
        - cd client
        - npm install
      script:
        - npm run test:unit